module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'false',
    AUTO_TYPING: 'false',
    AUTO_REPLY: 'true',
    AUTO_VOICE: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/HRIlSELlxO5JQo2gYL4MzV?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/qvwv3l.png',
    LOGO: 'https://files.catbox.moe/qvwv3l.png',
    NEWSLETTER_JID: '120363407284284185@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗔ꜱʜɪʏᴀ-𝗠ᴅ 5.0.0𝗩 🥷🇱🇰',
    OWNER_NAME: '𝗔ʏᴇꜱʜ 𝗧ʜᴇᴍɪʏᴀ 🥷🇱🇰',
    OWNER_NUMBER: '94752135878',
    WELCOME_OWNER: '94740285058',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '> *⛓ 𝐏ᴏᴡᴇʀᴇᴅ 𝐁ʏ 𝐀ꜱʜɪʏᴀ-𝐌ᴅ 𝗩.5 🥷🇱🇰*',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbC3JfG77qVXz1CbJM3l',
};
